PATHS="${HOME}/.gem/bin
/bin
/usr/bin
/usr/local/bin
/sbin
/usr/sbin
/usr/local/sbin
/snap/bin
/home/linuxbrew/.linuxbrew/bin
${HOME}/.local/bin
${HOME}/.rvm/bin
${HOME}/.cabal/bin
${HOME}/go/go1.14.2/bin
${HOME}/go/bin
${HOME}/.composer/vendor/bin
${HOME}/src/dot-files/bin
${HOME}/bin
${ROBO_ROOT}"
export PATHS
