PATHS="/sbin
/usr/sbin
/usr/local/sbin
/bin
/usr/bin
/usr/local/bin
/usr/local/opt/python@2/libexec/bin
/usr/local/opt/ruby/bin
/snap/bin
${HOME}/opt/python-2.7.11/bin
${HOME}/opt/python-3.5.1/bin
${HOME}/opt/ruby-2.5.0/bin
${HOME}/opt/git-2.11.0/bin
${HOME}/opt/multitail-6.4.2/bin
${HOME}/opt/lua-5.3.2/bin
${HOME}/opt/tidy-5.1.25/bin
${HOME}/opt/node-6.2.0/bin
${HOME}/opt/neovim/bin
${HOME}/opt/tmux-2.1/bin
${HOME}/opt/phantomjs-2.1.1/bin
${HOME}/opt/nss/bin
${HOME}/opt/zsh-5.2/bin
${HOME}/opt/task/bin
${HOME}/opt/thrift-0.9.3/bin
${HOME}/opt/maven-3.3.9/bin
${HOME}/opt/znc-1.6.3/bin
${HOME}/opt/gnupg-2.1.18/bin
${HOME}/opt/jdk8/bin
${HOME}/opt/dogecoin/bin
${HOME}/Library/Android/sdk/platform-tools
/Library/TeX/texbin
${HOME}/.gem/ruby/2.3.0/bin
${HOME}/.gem/ruby/2.5.0/bin
${HOME}/.local/bin
${HOME}/.rvm/bin
${HOME}/.cabal/bin
${HOME}/.composer/vendor/bin
${HOME}/.stack/snapshots/x86_64-linux/lts-5.17/7.10.3/bin
${HOME}/.stack/programs/x86_64-linux/ghc-7.10.3/bin
${HOME}/src/dot-files/bin
${HOME}/bin
${HOME}/src/arcanist/bin
${ROBO_ROOT}"
export PATHS
